version: "2"

services:
  app:
    image: golang:1.11.2 
    volumes:
      - .:/go/src/github.com/carojaspy/Part4-REST-API-ShoppingCart
    working_dir: /go/src/github.com/carojaspy/Part4-REST-API-ShoppingCart
    command: go run httpServer.go
    links:
      - db_shoppingcart
    depends_on:
      - db_shoppingcart
    ports:
      - 8080:8080

  db_shoppingcart:
    image: mysql:5.7
    volumes: 
      - ./mysql/data/dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopping_cart
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123qweasd
    networks: 
      - default
    ports: 
      - 3306:3306
    

